version: '2'
services:
    21windows-app:
        image: 21windows
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://21windows-postgresql:5432/21Windows
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=21windows-elasticsearch:9300
        ports:
            - 8080:8080
    21windows-postgresql:
        extends:
            file: postgresql.yml
            service: 21windows-postgresql
    21windows-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: 21windows-elasticsearch
